### ISSUE TITLE
AquaNereda Design note is misspelled.

### ISSUE THREAD

**Issue by chukon** [AquaAerobicSystemsInc/APD-Enhancements#9] opened 2018-07-17 11:41 UTC
The note should read proprietary technology. Fixing the master note will save time.

**Comment by phstanek** [comment] 2018-07-24 12:04
Chuck,

This may be a duplicate of Issue number 2 on the APD-Top-APD-Quick-Wins, which is currently waiting to be tested:

**Issue Number 2:  Design note #460 states that “AquaNereda is a propriety technology”. Propriety should be actually be proprietary.** 

Thanks,

Paul

**Comment by phstanek** [comment] 2018-08-01 13:55
This issue has been resolved under APD-Top-APD-Quick-Wins Issue 2 and can now be closed.

**Closed by phstanek** 2018-08-01 13:55 UTC
Labels: duplicate
