### ISSUE TITLE
The MiniCAS option in the control panel autobuild to work. 

### ISSUE THREAD

**Issue by chukon** [AquaAerobicSystemsInc/APD-Enhancements#6] opened 2018-07-17 11:37 UTC
We have the ability to put the numbers but don’t not translate to the BOM.

**Comment by phstanek** [comment] 2018-08-01 13:59
This is a duplicate of APD-Top-APD-Quick-Wins Issue 1:  The SBR Controls tab offers a box to enter the number of Mini-CAS pumps. Entering in the number of MiniCAS pumps does not add anything to the BOM.

**Comment by phstanek** [comment] 2018-08-03 13:29
APD-Top-APD-Quick-Wins Issue 1 has been resolved and closed, hence this duplicate issue shall also be closed.

**Closed by phstanek** 2018-08-03 13:29 UTC
Labels: duplicate
